### ISSUE TITLE
corrected_credset.R

### ISSUE THREAD

**Issue by chr1swallace** [annahutch/corrcoverage#13]
This file contains the lines 
```
  pp_ERR = function(Zj){
    exp.zm = Zj %*% Sigma
    mexp.zm = matrix(exp.zm, nrep, length(Zj), byrow=TRUE) # matrix of Zj replicated in each row
    zstar = mexp.zm+ERR
    bf = 0.5 * (log(1 - r) + (r * zstar^2))
    denom = logsum(bf)
    pp.tmp = exp(bf - denom)  # convert back from log scale
    pp.tmp / rowSums(pp.tmp)
  }
```
In this, I think zstar, and therefore bf are matrices.  But denom is a scalar. I think you need
```
denom=apply(bf,1,logsum)
```

**Comment by annahutch** [comment]
Yes - you are correct, thanks for spotting this! Doesn't seem to change the correction much but I am re-running simulations to check.

**Comment by chr1swallace** [comment]
Ok. Is this code used anywhere else in your package? Seems a standard bit of code, should be a function in its own right, that is then called by different functions

⁣http://chr1swallace.github.io​

**Comment by annahutch** [comment]
Yep sounds good, it is used throughout so will amend now

**Comment by chr1swallace** [comment]
Great to organise code like that.

But I see it won't actually make a difference because this line normalises

pp.tmp/rowSums(pp.tmp)

But if you get the denom right you won't need to normalise

⁣http://chr1swallace.github.io​

**Comment by annahutch** [comment]
Ah yes, so I no longer need the final   pp.tmp/rowSums(pp.tmp) line
