### ISSUE TITLE
CD fix

### ISSUE THREAD

**Issue by kkmann** [annahutch/corrcoverage#2]
@annahutch if you remove the `on:` part of the `.travis.yml`, CD should work, dunno why travis chokes on that atm...

https://github.com/annahutch/corrcoverage/blob/94addf354a4ba88c677c321bcf9b39f90581c29f/.travis.yml#L29-L32

**Comment by annahutch** [comment]
Thanks. Will do on my 'test' branch and open a pull request and merge etc. (for good practise ;))
